r = float(input('Quanto dinheiro você tem? BRL R$'))
print('Com base nas cotações do dia 18/04/2021, você pode comprar:')
print('Dólar (EUA)       - USD   ${:.2f}'.format(r / 5.5868))
print('Euro              - EUR   ¢{:.2f}'.format(r / 6.6902))
print('Libra Esterlina   - GBP   £{:.2f}'.format(r / 7.7221))
print('Iene (Japão)      - JPY   ¥{:.2f}'.format(r / 0.0513))
print('Dólar Australiano - AUD   ${:.2f}'.format(r / 4.3130))
print('Franco Suíço      - CHF Fr.{:.2f}'.format(r / 6.0746))
print('Dólar Canadense   - CAD   ${:.2f}'.format(r / 4.4659))
print('Yuan Chinês       - CNY   ¥{:.2f}'.format(r / 0.8567))
print('Peso Argentino    - ARS   ${:.2f}'.format(r / 0.0602))
print('Lira Turca        - TRY   ₺{:.2f}'.format(r / 0.6914))
