x = input('Escreva algo: ')
print('Tipo primitivo: {}'.format(type(x)))
print('É alfabético? {}'.format(x.isalpha()))
print('É numérico? {}'.format(x.isnumeric()))
print('É alfanumérico? {}'.format(x.isalnum()))
print('Possui somente valores da tabela ASCII? {}'.format(x.isascii()))
print('É um digito? {}'.format(x.isdigit()))
print('É decimal? {}'.format(x.isdecimal()))
print('É um identificador? {}'.format(x.isidentifier()))
print('Está em caixa alto? {}'.format(x.isupper()))
print('Está em caixa baixo? {}'.format(x.islower()))
print('É imprimível? {}'.format(x.isprintable()))
print('É um espaço? {}'.format(x.isspace()))
print('É um título? {}'.format(x.istitle()))
